# nestwatch uses Cornell's 6-letter codes.
nestwatch_categories <- list(
   passerines_use = c("easblu", "carwre", "carchi", "tuftit", "bkcchi",
                      "treswa", "wesblu", "astfly", "oaktit", "rewbla", "grycat",
                      "barswa", "blctit4", "bewwre", "moublu", "purmar", 
                      "whbnut", "mouchi", "towsol", "pygnut", "blujay", "veery",
                      "dickci", "woothr", "ovenbi1", "grcfly", "amerob",
                      "prowar", "bnhnut", "sonspa", "rebnut", 
                      "borchi2", "juntit1", "brnthr", "easpho", "saypho", 
                      "orcori", "wesjay", "chispa", "daejun", "bushti",
                      "cedwax", "weskin", "comgra", "purfin", "rusbla", "brebla",
                      "eastow", "balori", "robgro", "comrav", "lucwar",  
                      "wewpew", "yelwar", "bkbmag1", "whcspa",
                      "amedip", "amtspa", 
                      "buhvir", "easkin", "amecro", "lazbun",
                      "amegfi", "foxspa", "herthr", "gocspa", "bkhgro",
                      "logshr", "buggna", "bulori", "cliswa", "brncre", 
                      "reevir", "caltow", "snobun", "indbun", "comyel", 
                      "olsfly", "whevir", "norcro", "stejay", "sumtan",
                      "savspa", "graspa", "sctfly", "larspa", "bnhcow", 
                      "chswar", "spotow", "gyhjun", 
                      "warvir", "whbnut3", "louwat", "hoowar", "eawpew",
                      "blugrb1", "pacwre1", "fiespa", "winwre3", "bkcvir1",
                      "orejun", "rocwre", "pisjun", "horlar", 
                      "wesmea", "wrenti", "scatan", "gockin", "gchwar", "amerob1", 
                      "daejun5", "pinsis", "linspa", "casspa", "norpar", "gcrfin",
                      "amered", "slcjun", "wlswar", "yetwar", "purfin1", "fiscro",
                      "yetvir", "ruckin", "casfin",
                      "boboli", "btbwar", "clcspa", "banswa", "vesspa",
                      "whbnut2", "marwre"),
   empids = c("pasfly", "wilfly", "aldfly", "leafly", "acafly", "corfly", "hamfly",
              "gryfly", "bubfly", "yebfly"),
   saltmarsh = c("seaspa"),
   southern = c("houwre", "vigswa", "norcar", "houfin", "britit", "blkpho", "plsvir", 
                "phaino", "bktgna", "hooori", "belvir", "verfly", "verdin", "bncfly", 
                "easmea", "canwre", "cantow", "houwre1", "ducfly", "scoori", "pyrrhu",
                "grtgra", "clcrob", "houwre4", "belvir1", "cacwre", "gryvir", "nrwswa",
                "normoc", "benthr", "cubthr", "bktspa", "lesgol"),
   nonpasserines = c("bkbcuc", "killde", "norfli", "chbchi", "moudov", "wooduc", 
                     "hoomer", "wesowl1", "amekes", "easowl1", "calcon", "nswowl",
                     "commer", "comgol", "brnowl", "borowl", "reshaw", "allhum",
                     "wiltur", "dowwoo", "rebwoo", "yebsap", "rethaw", "brdowl",
                     "coohaw", "annhum", "cangoo", "labwoo", "grnher", "baleag",
                     "bkchum", "whwdov", "blkvul", "rebsap", "calhum", "comloo",
                     "pipplo", "mutswa", "burowl", "mallar", "grhowl", "grbher3",
                     "osprey", "gamqua", "greroa", "bbwduc", "chiswi", "haiwoo",
                     "coshum", "sposan", "swahaw", "goleag", "brthum", "whhwoo",
                     "calqua", "brwhaw", "bcnher", "rufhum", "perfal", "rthhum",
                     "miskit", "rehwoo", "truswa", "hergul", "horgre", "rengre",
                     "cogdov", "sancra", "pilwoo", "incdov", "rufgro", "norgos",
                     "turvul", "acowoo", "hrshaw", "batpig1", "ycnher", "mallar2",
                     "merlin", "ameavo", "piggui", "amewoo", "gilwoo", "resfli", 
                     "wesgre", "bknsti", "gofwoo", "whfibi", "rebmer", "amecoo",
                     "comnig", "shshaw", "reshaw5", "whip-p1", "yesfli", "belkin1",
                     "doccor", "rensap", "bongul", "buffle", "nutwoo", "crecar1", 
                     "yebcuc", "comeid", "dusgro", "amhgul1", "yertho1", "krthaw1",
                     "rxyfli", "loeowl", "mallar3", "gilfli", "ambduc", "ameoys",
                     "eassco1", "amekes1", "snoegr", "cacgoo1", "taimer1", "cangoo1",
                     "moudov2", "pibgre", "norsho", "turvul2", "kineid", "blkter",
                     "gubter1"),
   exotics_and_foreign = c("houspa", "eursta", "eucdov", "rocpig", "eutspa", 
                           "grnpar", "eurbla", "rocpig1", "compoo", "asbfly",
                           "varsun2", "blumoc", "jaweye", "btbrob1", "whiter",
                           "eardov1", "saffin",  "yebela1", "sicswi1", "crbthr1",
                           "saytan1", "cotfly1", "picpig2"),
   unknown = c("y00326", "y00033", "erthaw1", "y00701", "y00338", "gwcspa", 
               "bkebus", "x00195", "barswa5"),
   other = c("bluebi", "swallo", "bluebo1", "spizel", "wren1")
)

usethis::use_data(nestwatch_categories)
